services:
  - type: web
    name: ems-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: MONGO_URL
        sync: false
      - key: CLIENT_URLS
        sync: false
